### ISSUE TITLE
进京证这个现在还能用嘛

### ISSUE THREAD

**Issue by 15033388932** [amlun/enterbj#7]

**Comment by amlun** [comment]
@15033388932 目前sign还没搞出来，我会抽空hack一下。

**Comment by haoboys** [comment]
等你哦~..~！！！！

**Comment by gaoyuqiang** [comment]
之前没用过go，刚搭的环境，但是运行go build报错了，如何解决呢？
enterbj_request.go:4:2: cannot find package "github.com/amlun/enterbj/request" in any of:
	/usr/local/go/src/github.com/amlun/enterbj/request (from $GOROOT)
	/Users/a58/go/src/github.com/amlun/enterbj/request (from $GOPATH)
enterbj.go:6:2: cannot find package "github.com/amlun/enterbj/response" in any of:
	/usr/local/go/src/github.com/amlun/enterbj/response (from $GOROOT)
	/Users/a58/go/src/github.com/amlun/enterbj/response (from $GOPATH)
enterbj.go:7:2: cannot find package "github.com/google/go-querystring/query" in any of:
	/usr/local/go/src/github.com/google/go-querystring/query (from $GOROOT)
	/Users/a58/go/src/github.com/google/go-querystring/query (from $GOPATH)
enterbj.go:8:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/Users/a58/go/src/github.com/sirupsen/logrus (from $GOPATH)
gaoqingfangdeMacBook-Pro:enterbj-master gao$ go install
enterbj_request.go:4:2: cannot find package "github.com/amlun/enterbj/request" in any of:
	/usr/local/go/src/github.com/amlun/enterbj/request (from $GOROOT)
	/Users/a58/go/src/github.com/amlun/enterbj/request (from $GOPATH)
enterbj.go:6:2: cannot find package "github.com/amlun/enterbj/response" in any of:
	/usr/local/go/src/github.com/amlun/enterbj/response (from $GOROOT)
	/Users/a58/go/src/github.com/amlun/enterbj/response (from $GOPATH)
enterbj.go:7:2: cannot find package "github.com/google/go-querystring/query" in any of:
	/usr/local/go/src/github.com/google/go-querystring/query (from $GOROOT)
	/Users/a58/go/src/github.com/google/go-querystring/query (from $GOPATH)
enterbj.go:8:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/Users/a58/go/src/github.com/sirupsen/logrus (from $GOPATH)

**Comment by amlun** [comment]
@gaoyuqiang 
项目checkout到 $GOPATH/src/github.com/amlun/enterbj
然后用glide安装依赖包
另外注意目前 SIGN_URL 不对外开放
